### ISSUE TITLE
Boost_COMPILER content not compatible with CMake FindBoost

### ISSUE THREAD

**Issue by woodstock23** [boostorg/boost_install#9]
CMake expects the content of the variable Boost_COMPILER to start with a dash (e.g. "-vc142"), but the CMake scripts generated by a Boost build expect them without the dash (e.g. "vc142"), which are not passed through by CMake. This causes matching libraries to be rejected. A workaround is not to use those scripts by setting Boost_NO_BOOST_CMAKE to ON.

Tested on Windows 10 with Visual Studio 2019, CMake 3.14.4 and Boost 1.70.0.

**Comment by pdimov** [comment]
Thanks for the report; Boost_COMPILER handling was, apart from not handling `-vc142`, a bit broken for other reasons. Should be fixed in https://github.com/boostorg/boost_install/commit/9967d60ec1a6eaa8a4781f61f87d621a89b605a9 and https://github.com/boostorg/boost_install/commit/f24f8208155614a82e9c0e4bacde5559f5420b26.
